// <auto-generated />
namespace Poject_Photo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _09212020_newMG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09212020_newMG));
        
        string IMigrationMetadata.Id
        {
            get { return "202009300155268_09212020_newMG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
