//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendList
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string List { get; set; }
        public string Name { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
